import { table } from "./type";

export const data: table = {
  time: [
    "8:00 - 8:50",
    "8:50 - 9:40",
    "9:40 - 9:50",
    "9:50 - 10:40",
    "10:40 - 11:30",
    "11:30 - 12:20",
    "12:20 - 1:10",
    "1:10 - 2:50",
    "2:50 - 3:40",
  ],
  monday: [
    { period: "ENG" },
    { period: "PPS" },
    { period: "BREAK" },
    { period: "MATH" },
    { period: "POE" },
    { period: "BREAK" },
    { period: "NSO" },
    { period: "NSO" },
  ],
  tuesday: [
    { period: "MATH" },
    { period: "COUNSELLING" },
    { period: "BREAK" },
    { period: "PPS" },
    { period: "PPS" },
    { period: "BREAK" },
    { period: "VAC" },
    { period: "VAC" },
    { period: "ENG" },
  ],
  wednesday: [
    { period: "PHY" },
    { period: "PPS" },
    { period: "BREAK" },
    { period: "PHY" },
    { period: "BIO" },
    { period: "BREAK" },
    { period: "EVS" },
    { period: "POE" },
  ],
  thursday: [
    { period: "MATH" },
    { period: "ENG" },
    { period: "BREAK" },
    { period: "PHY" },
    { period: "POE" },
    { period: "BREAK" },
    { period: "EG" },
    { period: "LIBRARY" },
    { period: "EG" },
  ],
  friday: [
    { period: "PHY LAB" },
    { period: "PHY LAB" },
    { period: "BREAK" },
    { period: "PSP" },
    { period: "PSP" },
    { period: "BREAK" },
    { period: "MATH" },
    { period: "PPS" },
    { period: "PHY" },
  ],
};
